import { IMAGES } from "./images";

export const BRAND = {
  name: "HỆ THỐNG NHA KHOA ĐĂNG KHOA",
  shortName: "Nha Khoa Đăng Khoa",
  slogan: "Uy tín – Chất lượng – Tận tâm",
  hotline: "08.86.86.87.86",
  hotlineRaw: "0886868786",
  email: "info@hethongnhakhoadangkhoa.vn",
  website: "hethongnhakhoadangkhoa.vn",
  address: "345 - 347 Điện Biên Phủ, Khu Phố Ninh Phúc, Phường Ninh Thạnh, Tỉnh Tây Ninh",
  hours: "Thứ 2 – Thứ 7: 8:00 – 20:00 | Chủ nhật: 8:00 – 17:00",
  facebook: "https://www.facebook.com/nhakhoaphuongdong.bsdangkhoa/",
  zalo: "https://zalo.me/0886868786",
  messenger: "https://m.me/nhakhoaphuongdong.bsdangkhoa",
  youtube: "https://youtube.com/@nhakhoadangkhoa",
  tiktok: "https://www.tiktok.com/@nhakhoadangkhoa",
  mapEmbed:
    "https://maps.google.com/maps?q=345+Dien+Bien+Phu+Tay+Ninh+Vietnam&output=embed",
};

export const SERVICES = [
  {
    id: "implant",
    name: "Implant Nha Khoa",
    href: "/dich-vu/implant",
    short: "Cấy ghép implant chuẩn quốc tế",
    desc: "Phục hồi răng vĩnh viễn với công nghệ implant hiện đại, tích hợp hoàn toàn với xương hàm.",
    icon: "Zap",
    color: "#C89B3C",
  },
  {
    id: "nieng-rang",
    name: "Niềng Răng Chỉnh Nha",
    href: "/dich-vu/nieng-rang",
    short: "Niềng răng mắc cài, Invisalign",
    desc: "Chỉnh nha thẩm mỹ toàn diện với niềng truyền thống và hệ thống Invisalign trong suốt.",
    icon: "Smile",
    color: "#2563eb",
  },
  {
    id: "rang-su",
    name: "Răng Sứ Thẩm Mỹ",
    href: "/dich-vu/rang-su",
    short: "Veneer, Zirconia cao cấp",
    desc: "Phục hình răng sứ zirconia, veneer sứ – nụ cười hoàn hảo, tự nhiên như răng thật.",
    icon: "Star",
    color: "#7c3aed",
  },
  {
    id: "tay-trang",
    name: "Tẩy Trắng Răng",
    href: "/dich-vu/tay-trang",
    short: "Laser whitening chuyên nghiệp",
    desc: "Tẩy trắng răng bằng công nghệ laser tiên tiến, an toàn, hiệu quả vượt trội.",
    icon: "Sun",
    color: "#d97706",
  },
  {
    id: "noi-nha",
    name: "Điều Trị Nội Nha",
    href: "/dich-vu/noi-nha",
    short: "Điều trị tủy chuyên sâu",
    desc: "Chữa tủy răng, điều trị nhiễm trùng chuyên sâu với máy móc hiện đại, không đau.",
    icon: "Shield",
    color: "#059669",
  },
  {
    id: "nho-rang-khon",
    name: "Nhổ Răng Khôn",
    href: "/dich-vu/nho-rang-khon",
    short: "Nhổ không đau, phục hồi nhanh",
    desc: "Nhổ răng khôn bằng kỹ thuật tiên tiến, hạn chế tối đa đau đớn và thời gian hồi phục.",
    icon: "Activity",
    color: "#dc2626",
  },
];

export const DOCTORS = [
  {
    id: "nguyen-van-an",
    name: "BS. Nguyễn Văn An",
    title: "Giám đốc chuyên môn",
    specialty: "Implant & Phẫu thuật hàm mặt",
    experience: "15 năm kinh nghiệm",
    education: "Đại học Y Dược TP. HCM",
    bio: "Chuyên gia hàng đầu về cấy ghép implant và phẫu thuật hàm mặt tại Tây Ninh.",
  },
  {
    id: "tran-thi-mai",
    name: "BS. Trần Thị Mai",
    title: "Trưởng khoa Chỉnh nha",
    specialty: "Niềng răng & Chỉnh nha",
    experience: "12 năm kinh nghiệm",
    education: "Đại học Y Hà Nội",
    bio: "Chuyên gia chỉnh nha với chứng chỉ Invisalign quốc tế, đã điều trị hàng nghìn ca.",
  },
  {
    id: "le-minh-duc",
    name: "BS. Lê Minh Đức",
    title: "Bác sĩ thẩm mỹ nha khoa",
    specialty: "Răng sứ & Tẩy trắng",
    experience: "10 năm kinh nghiệm",
    education: "Đại học Y Dược Cần Thơ",
    bio: "Chuyên gia thẩm mỹ nha khoa, thiết kế nụ cười toàn diện với công nghệ CAD/CAM.",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Nguyễn Thị Hoa",
    service: "Niềng răng Invisalign",
    rating: 5,
    avatar: IMAGES.testimonials.nguyenThiKimHanh,
    text: "Tôi rất hài lòng với kết quả niềng răng tại đây. Các bác sĩ rất tận tâm, phòng khám hiện đại và sạch sẽ. Sau 18 tháng niềng, nụ cười của tôi đã thay đổi hoàn toàn!",
    date: "Tháng 3, 2024",
  },
  {
    id: 2,
    name: "Trần Văn Minh",
    service: "Implant nha khoa",
    rating: 5,
    avatar: IMAGES.testimonials.nguyenDinhPhuong,
    text: "Cấy implant tại Nha Khoa Đăng Khoa – quy trình chuyên nghiệp, không đau như tôi lo ngại. Sau 3 tháng đã có răng mới chắc chắn như răng thật. Rất đáng tin tưởng!",
    date: "Tháng 1, 2024",
  },
  {
    id: 3,
    name: "Lê Thị Lan",
    service: "Răng sứ thẩm mỹ",
    rating: 5,
    avatar: IMAGES.testimonials.truocSau,
    text: "Bọc sứ zirconia cho 4 răng cửa – kết quả đẹp hơn mong đợi. Màu sắc tự nhiên, không ai biết là răng sứ. Bác sĩ tư vấn rất kỹ, chi phí rõ ràng.",
    date: "Tháng 2, 2024",
  },
  {
    id: 4,
    name: "Phạm Thanh Tùng",
    service: "Tẩy trắng laser",
    rating: 5,
    avatar: IMAGES.testimonials.leThiThuy,
    text: "Tẩy trắng laser chỉ 1 buổi mà hiệu quả rõ rệt, răng trắng sáng hẳn. Kỹ thuật viên rất nhiệt tình, không ê buốt gì cả. Sẽ giới thiệu cho bạn bè!",
    date: "Tháng 4, 2024",
  },
  {
    id: 5,
    name: "Võ Thị Thu",
    service: "Nhổ răng khôn",
    rating: 5,
    avatar: IMAGES.testimonials.damThiLat,
    text: "Nhổ 2 răng khôn hàm dưới – bác sĩ thực hiện rất nhanh và nhẹ nhàng. Không đau trong khi nhổ, sau 2 ngày là ổn. Phòng khám rất sang trọng và chuyên nghiệp.",
    date: "Tháng 5, 2024",
  },
];

export const PROMOTIONS = [
  {
    id: 1,
    title: "Niềng Răng Ưu Đãi",
    discount: "Giảm 20%",
    desc: "Niềng răng mắc cài kim loại và Invisalign. Trả góp 0% lãi suất 24 tháng.",
    expiry: "31/07/2024",
    badge: "HOT",
    color: "from-amber-500 to-yellow-400",
    href: "/uu-dai",
  },
  {
    id: 2,
    title: "Răng Sứ Thẩm Mỹ",
    discount: "Giảm 15%",
    desc: "Bọc sứ zirconia cao cấp, veneer thẩm mỹ. Bảo hành 5 năm.",
    expiry: "31/08/2024",
    badge: "MỚI",
    color: "from-purple-500 to-indigo-500",
    href: "/dich-vu/rang-su",
  },
  {
    id: 3,
    title: "Implant Trọn Gói",
    discount: "Từ 15 triệu",
    desc: "Trọn gói cấy ghép implant Straumann, Osstem. Bao gồm mão sứ zirconia.",
    expiry: "30/06/2024",
    badge: "VIP",
    color: "from-emerald-500 to-teal-500",
    href: "/dich-vu/implant",
  },
  {
    id: 4,
    title: "Tẩy Trắng Laser",
    discount: "1.500.000đ",
    desc: "Tẩy trắng răng bằng công nghệ laser, hiệu quả ngay sau 1 buổi.",
    expiry: "30/09/2024",
    badge: "SALE",
    color: "from-blue-500 to-cyan-500",
    href: "/dich-vu/tay-trang",
  },
];

export { BLOG_POSTS, BLOG_CATEGORIES } from "./blog-posts";
export type { BlogPost } from "./blog-posts";
